platform :ios, '6.0'

pod 'Google-Maps-iOS-SDK'
pod 'DCModalSegue'
pod 'FlatUIKit'
pod 'AFNetworking', '= 1.3.2'
pod 'SKBounceAnimation', '~> 1.0.03'
pod 'KNSemiModalViewController', '~> 0.3'
pod 'RHAddressBook', '~> 1.0.2'
pod 'TwilioSDK', '~> 0.0.4'
